version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  ansible:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "a3:bd:0e:5d:8b:99:f1:7f:ea:f9:2f:43:ad:74:1b:9b"
      - run: apk add --update ansible
      - run: ansible-playbook main-remote.yml -i inventory

workflows:
  ansible-workflow:
    jobs:
      - ansible
