version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  ansible:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["05:f8:55:c8:2e:f3:f5:39:bb:1c:96:82:16:90:b9:88"]
      - run: 
        name: Install ansible
        command: apk add --update ansible openssh
      - run:
        name: Add server to known hosts
        command: ssh-keyscan -H 3.93.167.226 >> ~/.ssh/known_hosts
      - run: 
        name: Configure server
        command: ansible-playbook main-remote.yml -i inventory

workflows:
  ansible-workflow:
    jobs:
      - ansible
