version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  create-infrastructure:
    # docker:
    #   - image: amazon/aws-cli
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: aws cloudformation create-stack --stack-name AnsibleInfreTest --template-body file://template.yml

workflows:
  create-infrastructure-workflow:
    jobs:
      - create-infrastructure
